### ISSUE TITLE
Document Image Upload

### ISSUE THREAD

**Issue by eodmsabc** [swsnu/swpp2019-team1#1]
![Picture1](https://user-images.githubusercontent.com/15064156/66249958-ac09ee80-e776-11e9-8e54-c74975e25c3a.png)
![Picture2](https://user-images.githubusercontent.com/15064156/66249842-b32ffd00-e774-11e9-820f-6362fbea116b.png)

**Comment by eodmsabc** [comment]
![Picture2](https://user-images.githubusercontent.com/15064156/66249753-1caf0c00-e773-11e9-86d0-4444ec5492eb.png)

**Comment by eodmsabc** [comment]
![DB](https://user-images.githubusercontent.com/15064156/67115635-a8b43f80-f219-11e9-870c-3b249aa07908.png)

**Comment by eodmsabc** [comment]
Frontend UI Diagram for Sprint 2
![Picture1](https://user-images.githubusercontent.com/15064156/67136307-89400580-f25f-11e9-8237-ef33aca581ce.png)
![Picture2](https://user-images.githubusercontent.com/15064156/67136309-8a713280-f25f-11e9-9ea9-b7bebee3bc7e.png)

**Comment by helloing0119** [comment]
![components](https://user-images.githubusercontent.com/13051400/67138702-51968500-f282-11e9-9ffe-f90f6eaccb2a.png)
![component_relation](https://user-images.githubusercontent.com/13051400/67138706-5b1fed00-f282-11e9-94d2-dada82e94155.png)

**Comment by uyw4687** [comment]
![react-redux](https://user-images.githubusercontent.com/41810398/67138722-873b6e00-f282-11e9-97aa-9a7323217f69.jpg)

**Comment by uyw4687** [comment]
![view change](https://user-images.githubusercontent.com/41810398/67139237-b0f79380-f288-11e9-83fd-87dc7550e15c.jpg)

**Comment by uyw4687** [comment]
![view change](https://user-images.githubusercontent.com/41810398/68085199-c2908c00-fe81-11e9-9bac-23ded9fac269.jpg)

**Comment by uyw4687** [comment]
![react-redux](https://user-images.githubusercontent.com/41810398/70923791-cfe98a80-206b-11ea-82a5-7253acc7f897.jpg)

**Comment by uyw4687** [comment]
![view change](https://user-images.githubusercontent.com/41810398/70924767-708c7a00-206d-11ea-857c-2219ced8dfac.jpg)

**Comment by uyw4687** [comment]
![component_relation](https://user-images.githubusercontent.com/41810398/70926609-c0207500-2070-11ea-9ea3-597583b2a9c8.jpg)

**Comment by uyw4687** [comment]
![components](https://user-images.githubusercontent.com/41810398/70927654-bbf55700-2072-11ea-8fa9-2a707a042720.jpg)

**Comment by eodmsabc** [comment]
![Picture1](https://user-images.githubusercontent.com/15064156/71002400-8f007d00-2122-11ea-941c-21218361937a.png)
![ui](https://user-images.githubusercontent.com/15064156/71002408-9031aa00-2122-11ea-83c4-109b6ee28dbb.png)
