### ISSUE TITLE
Design Pattern Issue - Mini Profile Duplication

### ISSUE THREAD

**Issue by uyw4687** [swsnu/swpp2019-team1#26]
**Problem**
In match detail page, user can move on to host's profile page by clicking host's profile picture.
But this feature can be used in Navigation bar and chatroom also.
![image](https://user-images.githubusercontent.com/15064156/67941839-dcc83100-fc19-11e9-84ac-1f09d2bec9e0.png)

**Solution**
Make a separate component 'MiniProfile' which contains profile picture and username with button which will redirect user to profile page.

**Comment by eodmsabc** [comment]
각 컴포넌트마다 동작이 달라서 그대로 유지
