### ISSUE TITLE
React file structure

### ISSUE THREAD

**Issue by eodmsabc** [swsnu/swpp2019-team1#38]
비슷한 종류의 컴포넌트끼리 폴더로 묶어서 관리하면 좋을 것 같아요

예시) **containers**
- Header
- User
  - Auth
    - Sign In
    - Sign Up
  - Profile
    - Profile Edit
- Homepage
- Search
- Match
  - Create
  - Detail
    - Edit
  - Chatroom
- Footer

**Comment by HaeTheong** [comment]
동감합니다

**Comment by uyw4687** [comment]
How about putting Search in Match?
