### ISSUE TITLE
SWPP Bug report - can't sign up

### ISSUE THREAD

**Issue by sharkmir1** [swsnu/swpp2019-team1#90]
**Describe the bug**
I tried to sign up with various kinds of emails, but the system always says 'the email is duplicated'

**To Reproduce**
1. Go to sign up page
3. Type in all the information
4. Whenever i click sign up, it says 'email is duplicated'

**Comment by abcthing** [comment]
Same issue with email "2kv893mvkdfasdf@test.com", "sangbeom@test.com" etc...

**Comment by deploy-soon** [comment]
POST http://t1matchmaker.ml/api/user/signup/
403 forbidden error 때문에 확인이 안 되는 것 같습니다

**Comment by vionicbest** [comment]
직접 존재하는 이메일을 보냈을 때도 문제가 생깁니다

**Comment by deploy-soon** [comment]
그래도 id: test@test.com pw: test 로그인은 되네요

**Comment by sharkmir1** [comment]
> 그래도 id: [test@test.com](mailto:test@test.com) pw: test 로그인은 되네요

그거 제가 만들었습니다 ㅋㅋ

**Comment by HaeTheong** [comment]
CSRF 부분에 문제가 있어서 로그인은 되는데 가입이 안됐었네요. 죄송합니다 ㅜㅜ
