### ISSUE TITLE
SWPP Bug report - clicking on 'create now' does nothing

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team1#91]
**Describe the bug**
Landing page의 create now 버튼을 눌러도 아무 일도 일어나지 않습니다

**To Reproduce**
1. Go to Main page
2. Click on 'create now'
3. Nothing happens

**Comment by haesookim** [comment]
콘솔 확인 결과 403 에러가 발생합니다!

**Comment by HaeTheong** [comment]
로그인을 해야 create가 되게 구현해놔서 그렇습니다. 가입이 안됐던 점 죄송하고 로그인 페이지로 리다이렉트 되도록 고치겠습니다. 감사합니다!!
