### ISSUE TITLE
SWPP feature request - Footer position

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team1#93]
**Is your feature request related to a problem? Please describe.**
소소한 디자인적 요소이지만...! Footer position이 화면 아래쪽에 fix되어 있으면 좋겠습니다!

**Additional context**
<img width="1440" alt="Screen Shot 2019-12-05 at 6 41 29 PM" src="https://user-images.githubusercontent.com/13305988/70223352-f0256980-178e-11ea-90f6-04a00649405e.png">

**Comment by HaeTheong** [comment]
리뷰 감사합니다. 파이널까지 고치도록 하겠습니다 :)
