### ISSUE TITLE
Can't quit from match

### ISSUE THREAD

**Issue by dreamsh19** [swsnu/swpp2019-team1#95]
**Describe the bug**

**To Reproduce**
1. Go to specific match ' e.g) http://t1matchmaker.ml/match/1
2. Click on 'Quit'
3. See error
Always alert 'ERROR!' message. Cannot go back to main page
**Expected behavior**
Go back to main page

**Comment by HaeTheong** [comment]
아직 기능 구현이 안됐는데 미리 알려드리지 못했네요. 죄송합니다.

**Comment by uyw4687** [comment]
resolved
