### ISSUE TITLE
sign up이 되지 않은 상태에서의 behavior

### ISSUE THREAD

**Issue by ttoru96** [swsnu/swpp2019-team1#96]
**Describe the bug**
sign-up이 되지 않았을 때 search 창과 create now 버튼이 clickable 하지만 실제로 뭐가 동작하지는 않습니다. 

**To Reproduce**
sign-up과 로그인이 되지 않았다고 가정했을 때 
1-1. 서치 창에 뭔가를 입력하거나
1-2. create match 버튼을 눌렀을 때 

**Expected behavior**
clickable 하니까 뭔가 동작이 발생하기를 기대하게 되는데 아무것도 발생하지 않습니다. 
처음에 의도한 바가 search 바랑 create match 버튼이 로그인/sign-up이 안된 상태에서도 활성화되는 거였나요? 

**Screenshots**
<img width="758" alt="Screen Shot 2019-12-05 at 6 42 49 PM" src="https://user-images.githubusercontent.com/44546247/70223974-c9b3fe00-178f-11ea-88d8-abfae7bbe68a.png">
<img width="1440" alt="Screen Shot 2019-12-05 at 6 42 25 PM" src="https://user-images.githubusercontent.com/44546247/70223979-ccaeee80-178f-11ea-97f8-1fab9460d9db.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome

**Comment by HaeTheong** [comment]
search는 구현이 미완성이라 앞칸만 작동하는데 설명이 없어서이다들 못쓰셨을 것 같네요ㅜㅜ 죄송합니다.
create는 로그인을 해야 작동하게 구현해놔서 그렇습니다. 가입이 안됐던 점 죄송하고 로그인 페이지로 리다이렉트 되도록 고치겠습니다. 감사합니다!!
