### ISSUE TITLE
400 error on creating 'matches'

### ISSUE THREAD

**Issue by sharkmir1** [swsnu/swpp2019-team1#97]
**Describe the bug**
썸네일 업로드 창에서 이미지 파일이 아닌 다른 어떤 파일도 업로드가 되도록 되어 잇는데, 이런 파일을 업로드할시
400 error가 뜨며 다음 창으로 넘어가지 않습니다.

**To Reproduce**
1. 로그인하고 create match 화면으로 갑니다.
2. 이미지가 아닌 파일을 썸네일로 올립니다.
3. create 버튼을 누르면 400 error가 뜹니다.

**Comment by HaeTheong** [comment]
네, 저희가 이미지만 업로드 되게 막아놨는데 아무 설명이 없었네요. 메시지를 띄워 에러 처리하도록 하겠습니다. 감사합니다!
