### ISSUE TITLE
Jeehoon's Found Bugs

### ISSUE THREAD

**Issue by peterhyun** [swsnu/swpp2019-team1#98]
1. 싸인업이 안돼요ㅜㅜ 이메일 계속 듀플리케잇이라고 뜨네요

2. 로그인 안 한 채로 랜딩 페이지의 Search 누르면 그냥 하얀 빈칸 3개 나오는데 어떻게 사용하는지 모르겟네요.

3. 랜딩 페이지의 Create Now 눌러도 아무것도 안 일어나요... 콘솔 보면 에러 뜨네요.
POST http://t1matchmaker.ml/api/match/nlp/ 403 (Forbidden)

**Comment by HaeTheong** [comment]
csrf문제로 회원가입이 안됐던 점 죄송합니다. search는 아직 덜 구현되었는데 미리 말씀드리지 못했네요.. create는 로그인 시에만 작동하는데 로그인 된 상태가 아니면 로그인 페이지로 리다이렉트 되도록 바꾸겠습니다. 리뷰 감사합니다!
